dist: xenial   # required for Python >= 3.7
language: python

services:
  - docker

before_script:
  - scripts/build-aws.sh

script:
  - scripts/test-aws.sh

deploy:
  provider: script
  script: bash scripts/deploy-aws.sh
  on:
    branch: master