language: python

services:
  - docker

jobs:
  include:
    - stage: build
      script: scripts/build-aws.sh
    - stage: test
      script: scripts/test-aws.sh
    - stage: deploy
      script: scripts/deploy-aws.sh
